accounting/ui/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('accounting.ui.views',
    url(r'^$', 'home', name="home"),
    # currencies
    url(r'^currencies/$', 'currencies', name="currency_list"),
    url(r'^currency/add/$', 'currency_create', name="currency_create"),
    url(r'^currency/(?P<pk>\d+)/$', 'currency_detail',
                                            name="currency_detail"),
    url(r'^currency/(?P<pk>\d+)/delete/$', 'currency_delete',
                                            name="currency_delete"),
    # companies
    url(r'^companies/$', 'companies', name="company_list"),
    url(r'^company/add/$', 'company_create', name="company_create"),
    url(r'^company/(?P<pk>\d+)/$', 'company_detail',
                                            name="company_detail"),
    url(r'^company/(?P<pk>\d+)/delete/$', 'company_delete',
                                            name="company_delete"),
    url(r'^company/(?P<pk>\d+)/accountchart/$', 'company_create_chart',
                                            name="company_create_chart"),

    url(r'^company/(?P<pk>\d+)/fiscalyear/add/$', 'fiscalyear_create',
                                            name="fiscalyear_create"),
    # Fiscal years
    url(r'^fiscalyear/(?P<pk>\d+)/$', 'fiscalyear_detail',
                                            name="fiscalyear_detail"),
    url(r'^fiscalyear/(?P<pk>\d+)/delete$', 'fiscalyear_delete',
                                            name="fiscalyear_delete"),
    # Accounts
    url(r'^accounts/', 'accounts', name="account_list"),
    url(r'^account/add/$', 'account_create', name="account_create"),
    url(r'^account/(?P<pk>\d+)/$', 'account_detail',
                                            name="account_detail"),
    url(r'^account/(?P<pk>\d+)/delete/$', 'account_delete',
                                            name="account_delete"),
    # Ledgers
    url(r'^ledgers/', 'ledgers', name="ledger_list"),
    url(r'^ledger/add/$', 'ledger_create', name="ledger_create"),
    url(r'^ledger/(?P<pk>\d+)/$', 'ledger_detail',
                                            name="ledger_detail"),
    url(r'^ledger/(?P<pk>\d+)/delete/$', 'ledger_delete',
                                            name="ledger_delete"),
    # Moves
    url(r'^moves/', 'moves', name="move_list"),
    url(r'^move/add/$', 'move_create', name="move_create"),
    url(r'^move/(?P<pk>\d+)/$', 'move_detail',
                                            name="move_detail"),
    url(r'^move/(?P<pk>\d+)/delete/$', 'move_delete',
                                            name="move_delete"),
    url(r'^move/(?P<pk>\d+)/line/add/$', 'moveline_create',
                                            name="moveline_create"),
    # Move lines
    url(r'^moveline/(?P<pk>\d+)/$', 'moveline_detail',
                                            name="moveline_detail"),
    url(r'^moveline/(?P<pk>\d+)/delete/$', 'moveline_delete',
                                            name="moveline_delete"),
)

books/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'books.views.home', name='home'),
    # url(r'^books/', include('books.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^jsi18n/(?P<packages>\S+?)/$',
            'django.views.i18n.javascript_catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'', include("accounting.ui.urls")),
)

accounting/banks/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from accounting.models import Base, Company, Account, Ledger, Currency


class Bank(Base):
    code = models.CharField(max_length=10, verbose_name=_("Code"))
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    company = models.ForeignKey(Company)
    ## *partner


class BankAccount(Base):
    bank = models.ForeignKey(Bank)
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    account_number = models.CharField(max_length=30)
    iban = models.CharField(max_length=30, null=True, blank=True)

    account = models.ForeignKey(Account, related_name='banks',
                            null=True, blank=True)
    ledger = models.ForeignKey(Ledger, related_name='banks',
                            null=True, blank=True)
    costs_account = models.ForeignKey(Account, related_name='bank_costs',
                            null=True, blank=True)
    invoioce_ledger = models.ForeignKey(Ledger, related_name='bank_invoices',
                            null=True, blank=True)
    currency = models.ForeignKey(Currency, blank=True, null=True)

# BankStatment
   # *bank
   # initial_amount
   # final_amount
   # *move
#
# BankStatmentEntry
   # *statement
   # *account
   # *reference
   # *move_line
   # description

accounting/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.db.models import Sum
from django.core.exceptions import ValidationError
from django.utils.timezone import now

from mptt.models import MPTTModel, TreeForeignKey
from taggit.managers import TaggableManager
from currency_rates.models import Currency, default_currency


# Create your models here.
class Base(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def cache_key(self):
        tablename = self._meta.table
        return "%s:%s:%s" % (tablename, self.id, self.updated)

    def touch(self):
        ##
        self.save()

    @models.permalink
    def get_absolute_url(self):
        url = "%s_detail" % self._meta.object_name.lower()
        return (url, (), {'pk': self.id})


#def descendats(instance)
#   for field_name in instancel._meta.foreign_keys
#       field = getattr(instance, fieldname)
#       field.touch()
class Company(Base):
    code = models.CharField(max_length=10, verbose_name=_("Code"), \
                blank=True, null=True, unique=True)
    name = models.CharField(max_length=100, verbose_name=_("Name"), \
                blank=True, null=True, unique=True)
    currency = models.ForeignKey(Currency, default=default_currency,
                            blank=True, null=True)
    active = models.BooleanField(default=True)
    logo = models.ImageField(upload_to="logos", null=True, blank=True)

    # * partner
    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('name',)


FISCAL_YEAR_STATES = (
    ('draft', _('Draft')),
    ('open', _('Open')),
    ('closed', _('Closed')),
)


class FiscalYear(Base):
    company = models.ForeignKey(Company, related_name='fiscal_years')
    year = models.PositiveIntegerField()
    start = models.DateField(blank=True)
    end = models.DateField(blank=True)
    state = models.CharField(max_length=10, choices=FISCAL_YEAR_STATES,
                                default='draft')
    default = models.BooleanField(_('Default'), default=False,
        help_text=_('Make this the default for the company.'))

    def __unicode__(self):
        return "%s %s" % (self.company, self.year)

    class Meta:
        ordering = ('company', '-year')
        unique_together = ('company', 'year')

    def save(self, **kwargs):
        if self.default:
            try:
                default_year = FiscalYear.objects.get(default=True,
                                                        company=self.company)
            except self.DoesNotExist:
                pass
            else:
                default_year.default = False
                default_year.save()
        super(FiscalYear, self).save(**kwargs)


ACCOUNT_TYPES = (
    ('income', _('Income')),
    ('expense', _('Expense')),
    ('asset', _('Asset')),
    ('liability', _('Liability')),
    ('equity', _('Equity')),
)
# ('view', 'View'),
# ('other', 'Regular'),
# ('receivable', 'Receivable'),
# ('payable', 'Payable'),
# ('liquidity','Liquidity'),
# ('consolidation', 'Consolidation'),
# ('closed', 'Closed'),


class AccountType(Base):
    name = models.CharField(max_length=30, verbose_name=_("Name"))
    type = models.CharField(max_length=20, choices=ACCOUNT_TYPES,
                    verbose_name=_("Base type"))


class Account(MPTTModel, Base):
    company = models.ForeignKey(Company, related_name='accounts')
    parent = TreeForeignKey('self', null=True, blank=True,
                                related_name='children')
    code = models.CharField(max_length=10, verbose_name=_("Code"), \
                blank=True, null=True)
    name = models.CharField(max_length=100, verbose_name=_("Name"), \
                blank=True, null=True)
    type = models.CharField(max_length=20, choices=ACCOUNT_TYPES,
                    verbose_name=_("Account type"), default="auto")
    detail = models.BooleanField()
    reconciliable = models.BooleanField()
    seconday_currency = models.ForeignKey(Currency, blank=True, null=True)

    active = models.BooleanField(default=True)

    tags = TaggableManager(blank=True)

    class MPTTMeta:
        order_insertion_by = ['code']

    class Meta:
        unique_together = (('company', 'code'),)

    def clean(self):
        """ Validations """
        if not self.code.startswith(self.parent.code):
            raise ValidationError({'code': 'Incorrect code'})
        if self.parent and (self.parent.company != self.company):
            raise ValidationError({'fiscal_year': 'Incorrect company'})

    @property
    def credit(self):
        return MoveLine.objects.filter(account=self)\
                            .aggregate(Sum('credit'))['credit__sum'] or 0

    @property
    def debit(self):
        return MoveLine.objects.filter(account=self)\
                            .aggregate(Sum('debit'))['debit__sum'] or 0

    @property
    def balance(self):
        return self.debit - self.credit

    def __unicode__(self):
        return self.code


LEDGER_TYPES = (
    ('open', _('Open')),
    ('sale', _('Sale')),
    ('purchase', _('Purchase')),
    ('bank', _('Bank')),
)


class Ledger(Base):
    company = models.ForeignKey(Company, related_name='ledgers')
    code = models.CharField(max_length=10, verbose_name=_("Code"), \
                blank=True, null=True)
    name = models.CharField(max_length=100, verbose_name=_("Name"), \
                blank=True, null=True)
    type = models.CharField(max_length=20, choices=LEDGER_TYPES,
                    verbose_name=_("Ledger type"))
    active = models.BooleanField(default=True)

    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return self.name


MOVE_STATES = (
    ('draft', _('Draft')),
    ('done',  _('Done')),
)


class Move(Base):
    date = models.DateField(default=now)
    name = models.CharField(max_length=100, verbose_name=_("Name"), \
                blank=True, null=True)
    ledger = models.ForeignKey(Ledger, related_name="moves")
    fiscal_year = models.ForeignKey(FiscalYear)
    status = models.CharField(max_length=20, choices=MOVE_STATES,
                    verbose_name=_("Move satete"), default='draft')

    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return self.name

    @property
    def credit(self):
        return self.lines.aggregate(Sum('credit'))['credit__sum'] or 0

    @property
    def debit(self):
        return self.lines.aggregate(Sum('debit'))['debit__sum'] or 0

    @property
    def balance(self):
        return self.debit - self.credit


class MoveLine(Base):
    move = models.ForeignKey(Move, related_name='lines')
    account = TreeForeignKey(Account, related_name='moves',
                limit_choices_to={'detail': True})
    credit = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    debit = models.DecimalField(max_digits=20, decimal_places=2, default=0)

    due_date = models.DateField(blank=True, null=True)
    reference = models.CharField(max_length=20, blank=True, null=True)
    reconcile = models.ForeignKey("Reconcile", blank=True, null=True,
                    related_name='lines')

    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    currency = models.ForeignKey(Currency, blank=True, null=True)
    amount_currency = models.DecimalField(max_digits=20,
                            decimal_places=2, default=0)

    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return "%s %s %s" % (self.account, self.debit, self.credit)

    def clean(self):
        """ Validations """
        if self.move_id:
            if self.account.company != self.move.fiscal_year.company:
                raise ValidationError({'account':
                                    'Incorrect fiscal year account'})

        if self.credit == 0 and self.debit == 0:
            raise ValidationError({'credit':
                                    'Must inform credit or debit'})

        if not self.account.detail:
            raise ValidationError({'account':
                                    'Account does not accept moves'})


RECONCILE_STATES = (
    ('draft', _('Draft')),
    ('done', _('Done')),
)


class Reconcile(Base):
    status = models.CharField(max_length=20, choices=RECONCILE_STATES,
                    verbose_name=_("Reconcile status"))

    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return "%s %s %s" % (self.status, self.linea.count())

    def reconcile(self):
        """ validate same account, value = 0 """
        pass

accounting/ui/models.py
from django.db import models
from django.contrib.auth.models import User
from accouting.models import Base, Account


# class DashboardItem(Base):
#     user = models.ForeignKey(User)
#     item [chices...]
#     view_as [none, table, graphic, totals]
#     position


# class AccountMonitor(Base):
#     user = models.ForeignKey(User)
#     account = models.ForeignKey(Account)
#     view_as/visible...
#     alarm = [>,<,0,<>0]
#     alarm_level

accounting/ui/forms.py
import floppyforms as forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset

from accounting.models import Company, FiscalYear, MoveLine, Account
from accounting.chart_templates.models import AccountChartTemplate


class CompanyForm(forms.ModelForm):

    helper = FormHelper()
    helper.form_tag = False
    helper.help_text_inline = True
    helper.layout = Layout(
            Fieldset('Company data',  # fieldset label
                Field('code', placeholder="", css_class="span2"),
                Field('name', placeholder="", css_class="span4"),
                'active', 'currency', 'logo', 'tags',
            ))

    class Meta:
        model = Company
        widgets = {
            'code': forms.TextInput(attrs={'class': 'span1'}),
            'name': forms.TextInput(attrs={'class': 'span4'}),
        }


class CompanyCreateChartForm(forms.Form):
    template = forms.ModelChoiceField(AccountChartTemplate.objects.all())


class FiscalYearCreateForm(forms.ModelForm):

    class Meta:
        exclude = ['company']
        model = FiscalYear


class FiscalYearUpdateForm(FiscalYearCreateForm):

    class Meta:
        exclude = ['company', 'year']
        model = FiscalYear


class MoveLineCreateForm(forms.ModelForm):

    class Meta:
        exclude = ['move', 'reconcile']
        model = MoveLine


class AccountCreateForm(forms.ModelForm):
    class Meta:
        model = Account

accounting/banks/views.py
# Create your views here.

accounting/chart_templates/views.py
# Create your views here.

accounting/core/views.py
# Create your views here.

accounting/templates/accounting/account_form.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags %}
{% block content %}
<div class="row">
	<div class="span6">
		<h1>{% trans 'Account' %}</h1>
		<form method="POST" class="form-horizontal">
			{% csrf_token %}
			{{ form|crispy }}
			<div class="form-actions">
			    {% if object %}
			    	<input class="btn btn-primary" type="submit" value="{% trans 'Update account' %}"/>
					<a class="btn" href="{% url account_delete pk=object.pk %}">Delete</a>
			    {% else %}
			    	<input class="btn btn-primary" type="submit" value="{% trans 'Create account' %}"/>
			    	<input class="btn btn" type="submit" name="create_next" value="{% trans 'Create and add another' }"/>
			    {% endif %}
			</div>
		</form>
	</div>
	<div class="span6">
		{% if object %}
		<div>
			Credit : {{ object.credit }}
		</div>
		<div>
			Debit : {{ object.debit }}
		</div>
		<div>
			Balance : {{ object.balance }}
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}

accounting/templates/accounting/account_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="row">
    <div class="span12">
        <h1>{% trans 'Accounts' %}</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>{% trans 'Code' %}</th>
                    <th>{% trans 'Name' %}</th>
                    <th>{% trans 'Balance' %}</th>
                </tr>
            </thead>
            <tbody>
            {% for account in object_list %}
                <tr>
                    <td><a href="{{ account.get_absolute_url }}">{{ account.code }}</td>
                    <td><a href="{{ account.get_absolute_url }}">{{ account.name }}</td>
                    <td><a href="{{ account.get_absolute_url }}">{{ account.balance }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page=last">last</a>
                {% endif %}
            </span>
        </div>
        <a href="{% url account_create %}">Create account</a>
</div>
</div>
{% endblock %}

accounting/templates/accounting/company_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<h2>Companies</h2>
<form method="POST">
	{% csrf_token %}
    Delete 	{{ object }} ?
    <input type="submit" value="Delete"/>
</form>


{% endblock %}

accounting/templates/accounting/company_form.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags %}
{% block content %}
<div class="row">
	<div class="span12">
		<h1>{% trans 'Company' %}</h1>
	</div>
	<div class="span6">
		<form  method="POST" class="form-horizontal">
			{% crispy form %}
			<div class="form-actions">
			    {% if object %}
			    	<input class="btn btn-primary" type="submit" value="{% trans 'Update company' %}"/>
					<a class="btn" href="{% url company_delete pk=object.pk %}">{% trans 'Delete' %}</a>
					<a class="btn" href="{% url company_create_chart pk=object.pk %}">{% trans 'Create chart of accounts' %}</a>
			    {% else %}
			    	<input class="btn btn-primary" type="submit" value="{% trans 'Create company' %}"/>
			    	<input class="btn btn" type="submit" name="create_next" value="{% trans 'Create and add another' %}"/>
			    {% endif %}
			</div>
		</form>

	</div>
	<div class="span6">
	{% if object %}
		<h2>{% trans 'Fiscal years' %}</h2>
		<table class="table">
			<thead>
				<tr>
					<th>{% trans 'Year' %}</th>
					<th>{% trans 'State' %}</th>
					<th>{% trans 'Default' %}</th>
				</tr>
			</thead>
			<tbody>
				{% for fiscalyear in company.fiscal_years.all %}
				<tr>
					<td><a href="{{ fiscalyear.get_absolute_url }}">{{ fiscalyear.year }}</a></td>
					<td><a href="{{ fiscalyear.get_absolute_url }}">{{ fiscalyear.get_state_display }}</a></td>
					<td><a href="{{ fiscalyear.get_absolute_url }}">{{ fiscalyear.default }}</a></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<a class="btn" href="{% url fiscalyear_create pk=company.pk %}">{% trans 'Add fiscal year' %}</a>
	</div>
	{% endif %}
</div>
{% endblock %}

accounting/templates/accounting/company_list.html
{% extends "base.html" %}
{% block content %}

    <h2>Companies</h2>
    <ul>
        {% for company in object_list %}
            <li><a href="{{ company.get_absolute_url }}">{{ company.name }}</a></li>
        {% endfor %}
    </ul>

<a href="{% url company_create %}">Create Company</a>

{% endblock %}

accounting/templates/accounting/dashboard.html
{% extends "base.html" %}
{% block content %}

<pre>
Dashboad
--------
[Pending review]
[Drafts]
[Last entries]
[Last bank&cash]
[Last Invoices]
[alarms/monitors]

</pre>
{% endblock %}

accounting/templates/accounting/fiscalyear_form.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags %}
{% block content %}
<div class="row">
	<div class="span6">
		<h1>{% trans 'Fiscal year' %}</h1>

		{% trans 'Company' %} <a href="{{ company.get_absolute_url }}">{{ company }}</a>
		<form  class="form-horizontal">
			<fieldset>
				<legend>{% trans 'Fiscal year data' %}</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-actions">
			    {% if object %}
			    	<input class="btn btn-primary" type="submit" value="{% trans 'Update fiscal year' %}"/>
					<a class="btn" href="{% url company_delete pk=object.pk %}">{% trans 'Delete fiscal year' %}</a>
			    {% else %}
			    	<input class="btn btn-primary" type="submit" value="{% trans 'Create fiscal year' %}"/>
			    	<input class="btn btn" type="submit" name="create_next" value="{% trans 'Create and add another' %}"/>
			    {% endif %}
			</div>
		</form>
	</div>
	<div class="span6">
    {% if object %}
		<a class="btn" href="#">{% trans 'Open' %}</a>
		<a class="btn" href="#">{% trans 'Close' %}</a>
    {% endif %}
	</div>

</div>
{% endblock %}

accounting/templates/accounting/home.html
{% extends "base.html" %}
{% block content %}

    <h2>Menu</h2>
    <ul>
        <li><a href="{% url company_list %}">Companies</a></li>
        <li><a href="{% url account_list %}">Accounts</a></li>
        <li><a href="{% url ledger_list %}">Ledgers</a></li>
        <li><a href="{% url move_list %}">Moves</a></li>
        <li><a href="{% url currency_list %}">Currencies</a></li>
    </ul>
<pre>
Menu
----
- Accunts
- Reports
- Invoices
- Pending review
- Manual entries
   - Banc Journal
   - Cash journal
   - Manual move
- Settings
</pre>
{% endblock %}

accounting/templates/accounting/ledger_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<h2>Delete ledger</h2>
<form method="POST">
	{% csrf_token %}
    Delete 	{{ object }} ?
    <input type="submit" value="Delete"/>
</form>


{% endblock %}

accounting/templates/accounting/ledger_form.html
{% extends "base.html" %}
{% block content %}

<h2>Ledger</h2>
<form method="POST">
	{% csrf_token %}
    <table>
    	{{ form }}
    </table>
    <input type="submit" value="Create"/>
</form>

{% if object %}
	<a href="{% url ledger_delete pk=object.pk %}">Delete</a>


<h2>Last moves</h2>

{% for move in object.moves.all %}
	{{ move }}
{% endfor %}
{% endif %}

{% endblock %}

accounting/templates/accounting/ledger_list.html
{% extends "base.html" %}
{% block content %}

    <h2>Ledgers</h2>
    <ul>
        {% for ledger in object_list %}
            <li><a href="{{ ledger.get_absolute_url }}">{{ ledger.code }} {{ ledger.name }}</a></li>
        {% endfor %}
    </ul>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page=last">last</a>
        {% endif %}
    </span>
</div>

<a href="{% url ledger_create %}">Create ledger</a>

{% endblock %}

accounting/templates/accounting/move_confirm_delete.html
{% extends "base.html" %}
{% block content %}

<h2>Delete move</h2>
<form method="POST">
	{% csrf_token %}
    Delete 	{{ object }} ?
    <input type="submit" value="Delete"/>
</form>


{% endblock %}

accounting/templates/accounting/move_list.html
{% extends "base.html" %}
{% block content %}

    <h2>Moves</h2>
    <ul>
        {% for move in object_list %}
            <li><a href="{{ move.get_absolute_url }}">{{ move.ledger }} {{ move.date }}</a></li>
        {% endfor %}
    </ul>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page=last">last</a>
        {% endif %}
    </span>
</div>

<a href="{% url move_create %}">Create move</a>

{% endblock %}

accounting/templates/accounting/moveline_form.html
{% extends "base.html" %}
{% block content %}

<h2>Move line</h2>

Move : <a href="{{ move.get_absolute_url }}">{{ move }}</a>

<form method="POST">
	{% csrf_token %}
    <table>
    	{{ form }}
    </table>
    <input type="submit" value="Create"/>
</form>

{% if object %}
	<a href="{% url moveline_delete pk=object.pk %}">Delete</a>
{% endif %}

{% endblock %}